export const PROTOCOL_DAYS = [
  { title: 'Escolha as peças da campanha', description: 'Separe um lote de estoque parado, confira preços e defina uma meta realista para os próximos sete dias.', checks: ['Separei as peças e conferi os tamanhos', 'Conferi custos, preços e condições', 'Defini a meta do lote'], notification: 'Dia 1: escolha as peças e defina sua meta. Toque para abrir a missão.' },
  { title: 'Prepare suas clientes', description: 'Organize fotos e informações das peças. Convide clientes que já demonstraram interesse nesse perfil.', checks: ['Preparei fotos e detalhes das peças', 'Publiquei o convite da campanha', 'Convidei clientes interessadas'], notification: 'Dia 2: prepare o convite e avise suas clientes. Sua tarefa está pronta.' },
  { title: 'Coloque sua campanha na rua', description: 'Apresente as peças com tamanho, preço e forma de compra. Responda às conversas ao longo do dia.', checks: ['Publiquei as peças com preço e tamanho', 'Enviei a abertura às interessadas', 'Respondi às conversas recebidas'], notification: 'Dia 3: abra sua campanha. Veja a aula e apresente o lote às clientes.' },
  { title: 'Mostre as peças em combinações', description: 'Ajude a cliente a visualizar como usar cada peça e confira a margem antes de oferecer condições.', checks: ['Montei combinações reais', 'Conferi a margem das condições', 'Divulguei as combinações'], notification: 'Dia 4: mostre como usar as peças. Sua missão de combinações está aberta.' },
  { title: 'Retome as conversas abertas', description: 'Volte às clientes que demonstraram interesse e descubra o que falta para a decisão.', checks: ['Listei clientes interessadas', 'Retomei as conversas com contexto', 'Registrei dúvidas e pedidos'], notification: 'Dia 5: retome os atendimentos abertos. Veja por onde começar.' },
  { title: 'Dê destaque às peças restantes', description: 'Confira o que ainda está disponível e apresente essas peças de uma nova maneira.', checks: ['Conferi peças e tamanhos restantes', 'Preparei outra forma de apresentar', 'Divulguei a seleção atualizada'], notification: 'Dia 6: confira o lote restante e faça uma nova apresentação.' },
  { title: 'Feche a campanha e veja o resultado', description: 'Conclua atendimentos, confira lançamentos e anote o que funcionou para a próxima campanha.', checks: ['Comuniquei o encerramento real', 'Conferi pedidos e lançamentos', 'Anotei o que funcionou e o que mudar'], notification: 'Dia 7: feche a campanha e veja seu balanço final.' },
]
