'use client'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'

export default function SupportCenter({ cores, ouro, ouroGrad, whatsapp }) {
  const [tickets, setTickets] = useState([]), [aberto, setAberto] = useState(null), [novo, setNovo] = useState(false), [form, setForm] = useState({ subject: '', category: 'duvida', message: '' }), [resposta, setResposta] = useState(''), [mensagem, setMensagem] = useState(''), [carregando, setCarregando] = useState(true)
  async function api(body) { const { data: { session } } = await supabase.auth.getSession(); const resposta = await fetch('/api/suporte', { method: body ? 'POST' : 'GET', headers: { ...(body ? { 'Content-Type': 'application/json' } : {}), Authorization: `Bearer ${session?.access_token || ''}` }, body: body ? JSON.stringify(body) : undefined }); const data = await resposta.json(); if (!resposta.ok) throw new Error(data.error || 'Não foi possível concluir.'); return data }
  async function carregar() { setCarregando(true); try { const data = await api(); setTickets(data.tickets || []); if (aberto) setAberto((data.tickets || []).find(x => x.id === aberto.id) || null) } catch (e) { setMensagem(e.message) } finally { setCarregando(false) } }
  useEffect(() => { carregar() }, [])
  async function criar(e) { e.preventDefault(); try { await api(form); setForm({ subject: '', category: 'duvida', message: '' }); setNovo(false); setMensagem('✓ Chamado enviado.'); await carregar() } catch (e) { setMensagem(e.message) } }
  async function responder(e) { e.preventDefault(); if (!resposta.trim()) return; try { await api({ ticket_id: aberto.id, message: resposta }); setResposta(''); await carregar() } catch (e) { setMensagem(e.message) } }
  const campo = { width: '100%', boxSizing: 'border-box', background: cores.card2, color: cores.tx, border: `1px solid ${cores.borda}`, borderRadius: 10, padding: 12, font: 'inherit' }
  if (aberto) return <div><button onClick={() => setAberto(null)} style={{ background: 'transparent', color: ouro, border: 0, padding: 0, cursor: 'pointer', fontWeight: 800 }}>← Voltar aos chamados</button><div style={{ background: cores.card, border: `1px solid ${cores.borda}`, borderRadius: 14, padding: 18, marginTop: 14 }}><h2 style={{ color: cores.tx, fontSize: 18, margin: 0 }}>{aberto.subject}</h2><p style={{ color: ouro, fontSize: 11, fontWeight: 800 }}>{aberto.status.replaceAll('_',' ').toUpperCase()}</p><div style={{ display: 'grid', gap: 10 }}>{aberto.mensagens.map(msg => <div key={msg.id} style={{ justifySelf: msg.is_admin ? 'start' : 'end', maxWidth: '85%', background: msg.is_admin ? cores.card2 : '#2d270f', border: `1px solid ${msg.is_admin ? cores.borda : ouro}`, borderRadius: 12, padding: '10px 12px' }}><strong style={{ color: msg.is_admin ? ouro : cores.tx, fontSize: 11 }}>{msg.is_admin ? 'Equipe de suporte' : 'Você'}</strong><p style={{ color: cores.tx, fontSize: 13, lineHeight: 1.5, whiteSpace: 'pre-wrap', margin: '4px 0 0' }}>{msg.body}</p></div>)}</div>{aberto.status !== 'resolvido' && <form onSubmit={responder} style={{ display: 'flex', gap: 8, marginTop: 16 }}><input value={resposta} onChange={e => setResposta(e.target.value)} placeholder="Escreva uma mensagem..." style={{ ...campo, flex: 1 }} /><button style={{ background: ouroGrad, color: '#0A0A0A', border: 0, borderRadius: 10, padding: '0 16px', fontWeight: 900 }}>Enviar</button></form>}</div></div>
  return <div><div style={{ background: cores.card, border: `1px solid ${cores.borda}`, borderRadius: 14, padding: 18, marginBottom: 14, display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' }}><div><h2 style={{ fontSize: 19, margin: '0 0 5px', color: cores.tx }}>💬 Central de Suporte</h2><p style={{ fontSize: 13, color: cores.tx2, margin: 0 }}>Abra um chamado e acompanhe a resposta por aqui.</p></div><button onClick={() => setNovo(!novo)} style={{ background: ouroGrad, color: '#0A0A0A', border: 0, borderRadius: 10, padding: '11px 14px', fontWeight: 900, cursor: 'pointer' }}>+ Novo chamado</button></div>{mensagem && <p style={{ color: ouro, fontSize: 13 }}>{mensagem}</p>}{novo && <form onSubmit={criar} style={{ background: cores.card, border: `1px solid ${cores.borda}`, borderRadius: 14, padding: 16, display: 'grid', gap: 10, marginBottom: 14 }}><input required value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} placeholder="Assunto do chamado" style={campo} /><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} style={campo}><option value="duvida">Dúvida</option><option value="acesso">Acesso</option><option value="curso">Curso ou aula</option><option value="pagamento">Pagamento</option><option value="tecnico">Problema técnico</option><option value="outro">Outro</option></select><textarea required value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="Conte o que aconteceu..." rows={5} style={campo} /><button style={{ background: ouroGrad, color: '#0A0A0A', border: 0, borderRadius: 10, padding: 12, fontWeight: 900 }}>Enviar chamado</button></form>}{carregando ? <p style={{ color: cores.tx2 }}>Carregando...</p> : tickets.length ? tickets.map(item => <button key={item.id} onClick={() => setAberto(item)} style={{ width: '100%', textAlign: 'left', background: cores.card, border: `1px solid ${cores.borda}`, borderRadius: 12, padding: 14, color: cores.tx, cursor: 'pointer', marginBottom: 9 }}><strong>{item.subject}</strong><span style={{ display: 'block', color: cores.tx2, fontSize: 11, marginTop: 4 }}>{item.category} · {item.status.replaceAll('_',' ')} · {new Date(item.updated_at).toLocaleDateString('pt-BR')}</span></button>) : <div style={{ background: cores.card, border: `1px dashed ${cores.borda}`, borderRadius: 14, padding: 30, textAlign: 'center', color: cores.tx2 }}>Você ainda não abriu nenhum chamado.</div>}<a href={`https://api.whatsapp.com/send?phone=${whatsapp}&text=Suh%2C%20sou%20aluna%20e%20preciso%20de%20ajuda`} target="_blank" rel="noopener noreferrer" style={{ display: 'block', textAlign: 'center', color: ouro, fontSize: 12, marginTop: 16 }}>Caso urgente? Fale no WhatsApp</a></div>
}
